services:
  # Backend service
  - type: web
    name: cloudv-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend service
  - type: static
    name: cloudv-client
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      # Explicitly handle 404s by sending them to index.html
      - type: rewrite
        source: /[^.]*
        destination: /index.html
